CREATE TABLE devices (
    id VARCHAR(255) PRIMARY KEY,
    fw_version VARCHAR(255),
    nfc_uid VARCHAR(255),
    imei VARCHAR(255),
    mac_uwb VARCHAR(255),
    ip VARCHAR(255),
    devicetype VARCHAR(255),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE devicestatuses (
    id SERIAL PRIMARY KEY,
    deviceid VARCHAR(255) REFERENCES devices(id),
    timestamp TIMESTAMP NOT NULL,
    battery INTEGER,
    sos BOOLEAN,
    gps BOOLEAN,
    beacons BOOLEAN,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deviceevents (
    id SERIAL PRIMARY KEY,
    deviceid VARCHAR(255) REFERENCES devices(id),
    timestamp TIMESTAMP NOT NULL,
    event VARCHAR(255),
    sync BOOLEAN,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE deviceselftests (
    id SERIAL PRIMARY KEY,
    deviceid VARCHAR(255) REFERENCES devices(id),
    result VARCHAR(255),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gnsspositions (
    id SERIAL PRIMARY KEY,
    deviceid VARCHAR(255) REFERENCES devices(id),
    timestamp TIMESTAMP NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    height DOUBLE PRECISION,
    satquantity INTEGER,
    hdop DOUBLE PRECISION,
    vdop DOUBLE PRECISION,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE devicezonepositions (
    id SERIAL PRIMARY KEY,
    deviceid VARCHAR(255) REFERENCES devices(id),
    zoneid VARCHAR(255),
    timestamp TIMESTAMP NOT NULL,
    rssi INTEGER,
    temperature DOUBLE PRECISION,
    pressure DOUBLE PRECISION,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE zones (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    position VARCHAR(255),
    department VARCHAR(255),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employeezones (
    id SERIAL PRIMARY KEY,
    employeeid VARCHAR(255) REFERENCES employees(id),
    zoneid VARCHAR(255) REFERENCES zones(id),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE beacons (
    id VARCHAR(255) PRIMARY KEY,
    zoneid VARCHAR(255) REFERENCES zones(id),
    beacon_mac VARCHAR(255),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE departments (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE departmentzones (
    id SERIAL PRIMARY KEY,
    departmentid VARCHAR(255) REFERENCES departments(id),
    zoneid VARCHAR(255) REFERENCES zones(id),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE movements (
    id SERIAL PRIMARY KEY,
    deviceid VARCHAR(255) REFERENCES devices(id),
    from_zoneid VARCHAR(255) REFERENCES zones(id),
    to_zoneid VARCHAR(255) REFERENCES zones(id),
    timestamp TIMESTAMP NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE useractions (
    id SERIAL PRIMARY KEY,
    userid VARCHAR(255) REFERENCES users(id),
    action VARCHAR(255),
    timestamp TIMESTAMP NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


